title: CHINAFORUS
default_lang: ru
author:
  name: 'https://webgoose.ru'
  email: john@example.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
  keywords: wewe
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
team:
  -
    name: Алена
    role: 'Customers Suppport'
    img:
      user/themes/chinaforus/img/personal/1.jpg:
        name: 1.jpg
        type: image/jpeg
        size: 11958
        path: user/themes/chinaforus/img/personal/1.jpg
  -
    name: Владимир
    role: 'Founder & Art Director'
    img:
      user/themes/chinaforus/img/personal/1.jpg:
        name: 1.jpg
        type: image/jpeg
        size: 11958
        path: user/themes/chinaforus/img/personal/1.jpg
  -
    name: Дмитрий
    role: 'Design Director'
    img:
      user/themes/chinaforus/img/personal/1.jpg:
        name: 1.jpg
        type: image/jpeg
        size: 11958
        path: user/themes/chinaforus/img/personal/1.jpg
