title: CHINAFORUS
default_lang: ru
author:
  name: 'https://webgoose.ru'
  email: john@example.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
  keywords: wewe
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
