title: CHINAFORUS
default_lang: ru
author:
  name: 'https://webgoose.ru'
  email: support@webgoose.ru
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
  keywords: wewe
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
team:
  -
    name: Алена
    role: 'Customers Suppport'
  -
    name: Владимир
    role: 'Founder & Art Director'
  -
    name: Дмитрий
    role: 'Design Director'
0:
  email: ''
1:
  youtube: fdfdffgdg
2:
  instagram: ''
youtube: 'url pls'
email: chinaforuspost@gmail.com
instagram: 'https://instagram.com/chinaforus'
contacts:
  phone: '86 139 5794 5181'
  email: chinaforuspost@gmail.com
  instagram: 'https://instagram.com/chinaforus'
