extends@: default
child_type: item

rules:
  slug:
    pattern: "[a-z][a-z0-9_\-]+"
    min: 2
    max: 80

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        advanced:
          fields:
            overrides:
              fields:
                header.child_type:
                  default: item
        blog:
          type: tab
          title: Настройка страницы

          fields:

            content_title:
              type: spacer
              title: Параметры

            header.isNotIndex:
              type: toggle
              label: Это не главная страница?
              highlight: 1
              default: 1
              options:
                1: Да
                0: Нет
              validate:
                type: bool
                
            header.pageTemplate:
              type: text
              help: Выберите существующий шаблон страницы для услуги
              label: Шаблон страницы